### ISSUE TITLE
Contributing to nixpkgs

### ISSUE THREAD

**Issue by infinisil** [tweag/nix-hour#1]
How to get started contributing to [nixpkgs](https://github.com/nixos/nixpkgs/) with an example of updating some package, showing how to fork nixpkgs, clone it locally, figure out what to change, how to test the change, committing and pushing the change, then opening a PR for it and pinging the right people. Essentially a 0-100 for how to get started with nixpkgs contributing.

**Comment by Frostman** [comment]
I think the next mile would be interesting as well. Like how can you help with reviewing the PRs of other people, maybe test them, would it be helpful to review and put "LGTM", etc.?

**Comment by infinisil** [comment]
We looked at the basic contribution flow for nixpkgs in this weeks nix hour: https://www.youtube.com/watch?v=VpUHb-GagBE

@Frostman Sounds good, I'll leave this ticket open for your question :slightly_smiling_face:

**Comment by infinisil** [comment]
In the last Nix hour we addressed this partially: https://www.youtube.com/watch?v=QUnJ9q3Np7I&t=1399s

I'll close this issue for now, but feel free to ask more questions in this or a new issue :)
