### ISSUE TITLE
Using NixOS's testing libary

### ISSUE THREAD

**Issue by imsofi** [tweag/nix-hour#11]
When should you use it? What are some best practices and possible pitfalls when setting up a new NixOS test? What are some cool use-cases that are trivial to do with NixOS tests that otherwise may have been complicated to set up? Using Nix/NixOS tests in your own projects and trough CI. When to choose a derivation/passthru based test over a NixOS based test? Under the hood of a NixOS test (qemu), building faster running NixOS tests.

Feel free to build or take inspiration from this idea.

Similar question about testing derivations is here: #4.

**Comment by imsofi** [comment]
This might be the fastest an issue has been solved. While looking at the testing derivations issue, I noticed there is actually quite a bit of [discussion on NixOS tests](https://youtu.be/mOQI9Iiu4Uc?t=2565) at the end of Nix Hour 7. 😅

**Comment by infinisil** [comment]
Haha no problem, I think there's definitely more to talk about regarding NixOS tests :wink:

**Comment by imsofi** [comment]
Yeah. I personally would be interested in seeing is how a NixOS test could be used to test a full server deployment in your own project. However, i am unsure if this is a wise thing to do, as a lot of the documentation around NixOS tests only consider the use inside nixpkgs only.

**Comment by paraseba** [comment]
:+1:

**Comment by infinisil** [comment]
@paraseba See [here](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) for how to add the :+1: reaction, please add it to the top-level comment here :D

**Comment by imsofi** [comment]
Split out the parts about maintenance into #13

**Comment by infinisil** [comment]
We now looked at NixOS Tests more closely in [Nix Hour #20](https://www.youtube.com/watch?v=RgKl8Jue4qM), feel free to open more issues or come to the session directly if you have more questions!
