### ISSUE TITLE
nix build in nix hour #11 at 47:56 (youtube timing)

### ISSUE THREAD

**Issue by henrik-ch** [tweag/nix-hour#12]
When I try to follow along and build the flake as you do I get the following error message:

`❯ nix build --extra-experimental-features nix-command --extra-experimental-features flakes`
`warning: Git tree '/home/i97henka' is dirty`
`error: getting status of '/nix/store/glgrdiq4frv2zrdzrwnf0lgv
ld2fc822-source/github': No such file or directory`

Is there something wrong with my setup, or does it look more like I didn't type off the example correctly?

[flake.txt](https://github.com/tweag/nix-hour/files/10366141/flake.txt)
[default.txt](https://github.com/tweag/nix-hour/files/10366142/default.txt)

**Comment by henrik-ch** [comment]
I had a typo in my flake.nix - one { too much 😅 .

another thing that I believe made a difference for me, I did a git init and git add to the flake.nix and default.nix - something I saw recommended on reddit 😸. 

Sorry for disturbing and opening an issue unnecessarily!

**Comment by infinisil** [comment]
No problem, glad you figured it out!
