### ISSUE TITLE
The maintenance of a nix package/module

### ISSUE THREAD

**Issue by imsofi** [tweag/nix-hour#13]
Packaging has been noted in episode 9, https://www.youtube.com/watch?v=VpUHb-GagBE

But once you have something upstreamed or in your own repo. How do you go about maintaining it for the long term? The strategies with tooling/CI to help make it easier for you. The new `passthru.tests`, `passthru.updateScript` options (maybe mention nix-update), their value to a well maintained package.

**Comment by infinisil** [comment]
We talked more about this in [the last Nix Hour](https://www.youtube.com/watch?v=fd11ihDmPNc), as always feel free to open another issue if there's more though :)
