### ISSUE TITLE
Extending parameterized NixOS modules like `users.users.<name>`

### ISSUE THREAD

**Issue by con-f-use** [tweag/nix-hour#15]
### `<placeholder>` in module options

I'm really foggy in how somethings like the NixOS option [`users.users.<some_username>` ](https://search.nixos.org/options?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=users.users) works. I.e. how is that I can define something like:

```
users.users.confus = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]
    openssh.authorizedKeys.keys = [ ... ];
};
```

and the nix module system knows what type of option `extraGroups` is for my `confus` attribute and how to apply the extra groups. Also, how does one define such a parameterized "module", and especially, how does one extend it?

### Usecase for extending placeholder options

Eventually, I'd like to be able to define a module that extends that functionality. To be concrete, sshd has options called `AuthorizedPrincipalsFile` and `TrustedUserCAKeys` for [SSH Certificate Authentication](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_openssh_certificate_authentication) and I'd like to have some sort of means to do:

```
import = [ ./ssh-user-ca.nix ];

users.users.confus = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]
    openssh.authorizedPrincipals = [ "admins", "developers", "it-personnel" ];  # new functionality
};
```

Such that effectively the import of `./ssh-user-ca.nix` causes for every normal user in `users.users` an authorized principal file to created as if I had done:

```
environment.etc."ssh/auth_principals/confus".text = [ "admins", "developers", "it-personnel" ];  # what I want the new functionality to do
```

But if that's too much or too concrete, I'd be happy with some explanation on how constructs such as `some.option.<variable_parameter>.suboption = value` are done in the module system.

Examples for such constructs include:
- [`environment.etc.<filepath>`](https://search.nixos.org/options?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=environment.etc)
- [`virtualisation.sharedDirectories.<name>`](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=virtualisation.sharedDirectories)
- [`systemd.units.<name>`](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=systemd.units)
- [`networking.interfaces.<name>`](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=networking.interfaces.%3Cname%3E.)

**Comment by con-f-use** [comment]
As a small footnote you could maybe explain, why the word "users" is repeated, meaning, why is it `users.users.<name>` and not just `users.<name>`?

**Comment by infinisil** [comment]
We looked at this in [today's Nix hour](https://www.youtube.com/watch?v=lO0x0Kk9wTM), I hope this helps! Feel free to open another issue if you have more questions :)

**Comment by con-f-use** [comment]
Thanks a bunch. You did a very good job, Silvan! That was more than I could have hoped for. You have the uncanny ability to anticipate every question I could have had, even the ones that would never occur to me, until I actually tried to write that extension myself. I'm very impressed.
Also thanks to Tweag that they sponsor the nix hour and let their people take time off their other duties so they can educate the community.

**Comment by con-f-use** [comment]
```
{ config, lib, ... }:
{
  options.users.users = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule (
        { name, config, ... }: {
          options.openssh.authorizedPrincipals = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [];
          };
          config.extraGroups = config.openssh.authorizedPrincipals;
        }
      )
    );
  };

  config = lib.mkIf config.services.openssh.enabled {
    environment.etc = lib.mapAttrs' (
      _: { openssh, name, ... }: {
        name = "sshd/principals/${name}";
        value.text = ''${lib.strings.concatMapStrings (x: x + "\n") openssh.authorizedPrincipals}'';
      }) (lib.filterAttrs (_: u: u.openssh.authorizedPrincipals != []) config.users.users)
    ;

    services.openssh.extraConfig = ''
        AuthorizedPrincipalsFile /etc/sshd/principals/%u
        TrustedUserCAKeys /etc/ssh/trusted-user-authorities.crt
      '';
  };
}

# Configure user authority like so:
# config.environment.etc."ssh/trusted-user-authorities.crt".source = pkgs.fetchurl {
#   url = "...";
#   hash = "";  # Mandatory! Verify!
#   curlOpts = "--insecure";  # fine because hash is checked
# };
```
Btw. this is the first draft based on the nix-hour. I'll probably do the `authorizedPrincipals.<name> = true/false` definition instead of the list, as was mentioned in the end of the video. I'll also like define an `services.openssh.TrustedUserCA` option and only apply config changes if both openssh is enabled and that is configured. But it's very late and I cannot figure out the syntax. Any thoughts?

**Comment by infinisil** [comment]
I'm glad it was this helpful, I appreciate the feedback a lot :heart:!

Yeah an option like this seems upstreamable to me, it should fit well :slightly_smiling_face:

**Comment by con-f-use** [comment]
Just wanted to say, this feature was introduced in https://github.com/NixOS/nixpkgs/pull/259425
