### ISSUE TITLE
Writing your own deployment tool

### ISSUE THREAD

**Issue by soupglasses** [tweag/nix-hour#18]
As `nixos-rebuild` is a single relatively easy to read bash script, it could be a fun exercise to explore what steps one would need to do to recreate it. What steps it verifies, which it does not, how it ensures a build goes successfully and when not. Things like `activationScripts`, how they connect into the deployment.

A fun example for a custom activation script is `upgrade-diff` by Mic92 https://github.com/numtide/srvos/blob/main/nixos/common/upgrade-diff.nix

One can also bring in colmena and deploy-rs as it is built on [commands like `nix copy`](https://github.com/serokell/deploy-rs/blob/8c9ea9605eed20528bf60fae35a2b613b901fd77/src/push.rs#L171-L179).

**Comment by infinisil** [comment]
I dived into `nixos-rebuild` in [the last Nix Hour](https://www.youtube.com/watch?v=aQJE4ZxD3cc&list=PLyzwHTVJlRc8yjlx4VR4LU5A5O44og9in&index=1), which should help a bit, though it doesn't fully answer this question :)
