### ISSUE TITLE
New features of nixpkgs and Nix

### ISSUE THREAD

**Issue by infinisil** [tweag/nix-hour#2]
What are some newer interesting nixpkgs/Nix features? What old things do they deprecate, are they stable already, should those be used?

**Comment by 573** [comment]
Probably related #9

**Comment by infinisil** [comment]
I'm gonna close this since it's never really done, but I might occasionally come back to this when I have some interesting new thing to talk about. But feel free to open another issue if you're interested in having some specific new feature you're curious about :)
