### ISSUE TITLE
Howto: Create a package that does not exist yet in https://search.nixos.org/packages

### ISSUE THREAD

**Issue by we-do-it-lu** [tweag/nix-hour#21]
It would be interesting to see how a package is created from zero: 
- High-level considerations
- Process of creating it
- Loading it in nix once done

I am thinking of a very simple software, e.x. sendmidi ([https://github.com/gbevin/SendMIDI](https://github.com/gbevin/SendMIDI)) which is very simple I guess. 

Thank you in advance.

**Comment by infinisil** [comment]
Please take a look at [this tutorial](https://nix.dev/tutorials/packaging-existing-software) and let me know if you have any other questions!
