### ISSUE TITLE
Override / overlay for VSCodium to change binary path

### ISSUE THREAD

**Issue by carlwickham** [tweag/nix-hour#26]
Hi Silvan and Tweag people,

Some time ago I switched from VSCode to open alternative VSCodium. I ingrained in my mind to start the editor with `code` so I created a shell script script `/bin/code` that starts `/bin/codium` (I think such shell script is called [wrapper](https://nixos.wiki/wiki/Wrappers_vs._Dotfiles)).

But when using remote feature where VSCodium copies itself to a remote host via SSH, the binary is again `codium` and of course the shell script is not copied...

Based on my understanding it is possible to create override (or is it call overlay?) to modify the VSCodium package so the actual binary is `/bin/code` and not `/bin/codium`. Could you please show in Nix Hour how to do that?

Thank you for excellent youtube! Very educational!

Carl

**Comment by MatXron** [comment]
And maybe start with explaining basics - when and why to use Overrides / overlays.

**Comment by con-f-use** [comment]
I think that would be very hard with nix. The key part here is:

> ...VSCodium copies itself to a remote host via SSH..

I.e. nix would have to patch the VSCodium source code itself (the part that does the copying) so it copies over or creates the link `/bin/code --> /bin/codium`, too. That would also mean, nix would probably have to build that patched version from source, since it is not in any subsitutor/binary-cache.

**Comment by ben-tiky** [comment]
In past I built Codium and it is "just" a patch set on top of VSCode. So the only thing needed to remove variable that specifies "codium" as the output file. Remove it or change it to "code" so it has no effect.

**Comment by con-f-use** [comment]
So no need to re-compile?

**Comment by ben-tiky** [comment]
Re-compilation will be needed. With different configuration - all that will be needed is to replace `codium` by `code` in the config... (or possibly uncomment it)

**Comment by infinisil** [comment]
We looked a bit at this in [Nix Hour 50](https://www.youtube.com/live/W5ivK5PhDlY?feature=shared&t=2640)!

I'll keep this open because we didn't address everything :)

**Comment by infinisil** [comment]
We looked at this in more detail in [Nix Hour 53](https://www.youtube.com/live/I3ccgcms0ck?feature=shared&t=71)!
