### ISSUE TITLE
Can I extend `nixpkgs.lib` or `builtins` with my own library function?

### ISSUE THREAD

**Issue by con-f-use** [tweag/nix-hour#28]
Say I had a custom fetcher, that I wanted to use everywhere in a flake:

```nix
  fetchPrivatePyPi= url: builtins.fetchurl (
    let
      components = builtins.match "(.*)#sha256=([a-fA-F0-9]+).*" url;
    in {
      url = "http://my-custom-pypi.org/company/" + builtins.head components;
      hash = "sha256:" + lib.last components;
    }
  );
```

How would I make that similarly accessible as `builtins.fetchurl`?

I mean, sure, I could just import a file or use an overlay or whatever, like an animal. But maybe there's a way to extend built-ins or a way to specify a "global library" for use inside a flake. There's a kinda related [nixpkgs issue](https://github.com/NixOS/nixpkgs/pull/157056) that Silvan already participated in.

**Comment by infinisil** [comment]
@con-f-use Oh yeah forgot to push it! Here it is: https://github.com/tweag/nix-hour/tree/master/32 :smile:
