### ISSUE TITLE
What arguments are allowed for a nixos configuration?

### ISSUE THREAD

**Issue by Panke** [tweag/nix-hour#34]
The nixos manual says a configuration can have the two arguments `config` and `pkgs`. 

Later it also uses `modulesPath` as an argument (like many examples from the web I refer to as well.). 
What other arguments can be used? Where is that determined?

Related question: I want to describe multiple nixos configuration in a single flake. How can I refer between those configurations? E.g. use a port value from config A as a setting in config B?

**Comment by infinisil** [comment]
We looked into the argument question in [todays Nix Hour](https://www.youtube.com/live/jb36PfG28W8?feature=shared&t=1420)!

**Comment by Panke** [comment]
Thanks! I just watched the recording and indeed it answers the question quite well!

**Comment by infinisil** [comment]
> Related question: I want to describe multiple nixos configuration in a single flake. How can I refer between those configurations? E.g. use a port value from config A as a setting in config B?

And we looked at this in todays [Nix Hour 48](https://www.youtube.com/watch?v=3XAJDzrMZqA&list=PLyzwHTVJlRc8yjlx4VR4LU5A5O44og9in&index=1) :)
