### ISSUE TITLE
What are the Tangible Benefits of the `finalAttrs` Pattern?

### ISSUE THREAD

**Issue by Lord-Valen** [tweag/nix-hour#35]
Introduced in https://github.com/NixOS/nixpkgs/pull/119942, Robert states a few advantages of "overlay style overridable recursive attributes". I think it would be useful to demonstrate the cases where `rec` is insufficient or undesirable and show how the `finalAttrs` pattern addresses them.

**Comment by infinisil** [comment]
We looked into this in [todays Nix Hour](https://www.youtube.com/live/jb36PfG28W8?feature=shared&t=90) :smiley:
