### ISSUE TITLE
Define shell function in mkShell?

### ISSUE THREAD

**Issue by con-f-use** [tweag/nix-hour#36]
I can define extra environment variables in mkShell like so:

```nix
mkShell {
    packages = [ ... ];
    shellHook = ''echo "$EXTRA_ENVIRONMENT_VARIABLE"'';
    EXTRA_ENVIRONMENT_VARIABLE = "woohoo";
}
```
is there a nice way to  define and use a short bash function in a similar way? 

Meaning `extra_function = mkFunc "greentext" ''echo -e "\033[0;32m$*\033[0m"'';` and then you can call it in the hooks like `shellHook = ''greentext "this is green now"'';`. Should there be?

Edit:
Other minor things to explain: `nix-shell` vs. `nix shell` vs. `nix develop` with respect to flakes and non-flakes.

**Comment by infinisil** [comment]
We talked about this [in Nix Hour #44](https://www.youtube.com/live/rio7Iv-PHnA?feature=shared&t=2008)! Feel free to open another issue if something was unclear or needs more details though :)
