### ISSUE TITLE
How could I put some directories in `/etc`

### ISSUE THREAD

**Issue by GiulioCocconi** [tweag/nix-hour#38]
I know I can put single files using `environment.etc.<name>` but how can I link an entire folder to `/etc`?

**Comment by con-f-use** [comment]
As long as nix is aware, [this](https://search.nixos.org/options?channel=23.05&show=environment.etc.%3Cname%3E.source) will work:
```nix
{
environment.etc."some/dir".source = ../dir/relative/to/source;
}
```
