### ISSUE TITLE
Building latest cPython from source

### ISSUE THREAD

**Issue by MaxwellDupre** [tweag/nix-hour#39]
Hi,
I want to build the latest cpython 3.13 from source.
I have searched the web and cant find anything that helps.
I have tried creating fhs and this works but not exactly what I need.
I can build python, however when I try to test `-m test` I get failures because of restrictions in the nix shell, e.g. network/socket creation error.
I note that there are some scripts in nixpkgs that build python from source.
And I suppose I could adapt to compile from source.
But I have a problem as to witch script do I use and what command?
I would then need to add patches at the very least the ones shown in nixpkgs.
Then I would like to test the built python with `-m test` without any restrictions.
I am not familiar with nix testing but would be grateful for insight on how testing of python is done.
This leads me to a secondary question but very important to me:
Once a derivation is created in result/$out how is it made globally available?
What I mean is how do I or anyone logged in run that derivation?
(without having to go to that [nix]shell)
A docker would provide a solution but its a lot of effort, at least for me.
The nix hour is amazing! And really helpful could I suggest some of the code is added to the nix docs. I could add to the Wiki if its allowed?
Thanks
Mike

**Comment by infinisil** [comment]
Thanks for the question and joining the Nix Hour! For others, we looked at this in [today's Nix Hour #43](https://www.youtube.com/watch?v=T79B4t80QZ4&list=PLyzwHTVJlRc8yjlx4VR4LU5A5O44og9in&index=1&pp=iAQB), the files of which are here: https://github.com/tweag/nix-hour/tree/master/43
