### ISSUE TITLE
Why is `builtins.split` so weird?

### ISSUE THREAD

**Issue by con-f-use** [tweag/nix-hour#42]
I scratch my head every time I look at [it](https://github.com/NixOS/nix/pull/1516) and then end up using `lib.strings.splitString` instead. I couldn't find any usage that actually does something with the interleaving. I don't know what rode the [people](https://github.com/NixOS/nix/pull/1516) that thought it should be like this. Please enlighten me, if you can :grin: It's easily the weirdest part of the nix language.

![image](https://github.com/tweag/nix-hour/assets/11145016/d1bd5202-9165-41da-a6da-55cd1582a056)

**Comment by infinisil** [comment]
We looked at this [in Nix Hour #44](https://www.youtube.com/live/rio7Iv-PHnA?feature=shared&t=36) :)
