### ISSUE TITLE
How to make a new app globally available

### ISSUE THREAD

**Issue by MaxwellDupre** [tweag/nix-hour#43]
Once a derivation is created in result/$out how is it made globally available?
What I mean is how do I or anyone logged in run that derivation?
(without having to go to that [nix]shell)

**Comment by infinisil** [comment]
We looked at this [in Nix Hour #44](https://www.youtube.com/live/rio7Iv-PHnA?feature=shared&t=535)! This could be covered in more detail though, feel free to open another issue if you have a specific question!
