### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by idontgetoutmuch** [tweag/nix-hour#51]
The instructions for contributing are quite demanding. Could you give a gentle introduction on how to contribute?

**Comment by Animeshz** [comment]
Yeah, there's no structured way as there's no github issue template here in the repository, a standard guideline or a template would be great add-on!

**Comment by infinisil** [comment]
@Animeshz Pretty sure @idontgetoutmuch meant how to contribute to Nixpkgs! The nix-hour repository isn't really intended for contributions. Would be good to have more descriptive issues to avoid confusion though :)

But indeed we looked at this in this weeks [Nix Hour 49](https://www.youtube.com/live/ylZSeCvmvGE?si=XIUDsdyA1hYhm5DZ), we mainly went through most of https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md :)

If there's other questions, feel free to open another issue!

**Comment by Animeshz** [comment]
Oh ok, nvm, thanks for resolving the confusion :sweat_smile:.
