### ISSUE TITLE
Writing NixOS Modules

### ISSUE THREAD

**Issue by J-Swift** [tweag/nix-hour#52]
As I've gotten more into NixOS I've realized a lot more about module syntax than I knew before, and have confused myself as well. It would be nice to see a focused breakdown of NixOS modules and the many ways to declare/import them.

Things like:
- `modules = [./path-to-module.nix]` vs `modules = [(import ./path-to-module.nix {})]`
- with/without `imports` attr
- with/without `config` attr
- as a function that returns a module vs non-function

The last one was one that got me recently. I was trying to declare a module in my flake.nix and didn't have access to `config` "yet" in the scope I was in doing something like this:

```
modules = [
     {
          foo.path = config.service.bar.path; # error, config doesnt exist
     }
]
```

I ended up solving it like this:

```
modules = [
     ({ config, ... }:    
     {
          foo.path = config.service.bar.path;
     })
]
```

Related as a followup: it would be nice to see a detailed breakdown of all the standard module args you can "magically" reference (e.g. lib, pkgs, config) and how/where those are declared.

**Comment by Animeshz** [comment]
Might be related to (OR helpful to look at): [Nix Hour 19](https://www.youtube.com/watch?v=cZjOzOHb2ow)

**Comment by asymmetric** [comment]
Also, the Doc Team is working on a tutorial that answers some of your questions: https://github.com/NixOS/nix.dev/pull/645

Although being a tutorial, and not a reference, it might be hard to quickly find the answers you're looking for, they're kind of buried within a lot of.. tutorial.

@roberth is working on a reference, but it still needs some work: https://github.com/NixOS/nixpkgs/pull/240531/

**Comment by J-Swift** [comment]
@Animeshz that video is really useful, thank you. Haven't finished it to see if it addresses all of the above, but its definitely a good chunk of it.

**Comment by infinisil** [comment]
We decided to focus on this topic for this weeks Nix Hour, this Friday at 18:00 CET! Though we're making it a bit more general, the title being "Writing NixOS Modules". If you have any questions about this topic, either:
- Ask them in this issue with a comment
- Join [the meeting](https://meet.zrh.init7.net/nix-hour) and ask using voice or chat

And if you just want to listen in, it's going to be streamed to YouTube [here](https://www.youtube.com/watch?v=N7hFP_40DJo&list=PLyzwHTVJlRc8yjlx4VR4LU5A5O44og9in&index=1&pp=iAQB) :slightly_smiling_face:

**Comment by anstylian** [comment]
I have this toy project that I am also using to get my self familiar with nix-flakes and NixOs. 
https://github.com/anstylian/petclinic

Currently I have the following question, what is the proper way to deploy files that are needed by the application, either at run time, or during installation.

Also if you would like to review it, and point out the newbie mistakes I have its really welcome :).

**Comment by infinisil** [comment]
Since there's a lot of questions that haven't been addressed in last weeks Nix Hour, we'll do another one on this topic this week!

Time: Tomorrow, Thursday [18:00 CET](https://time.is/1800_in_CET)
Meeting: https://meet.zrh.init7.net/nix-hour
Live stream: https://www.youtube.com/live/TGsj8lEe8t0?feature=shared

**Comment by infinisil** [comment]
I think we adequately covered this topic in the last two Nix hours (links above), so let's close this issue for now. If you have anything else to talk about, please open a new one.
