### ISSUE TITLE
topic: fetchZip exceeds hydra output size limit

### ISSUE THREAD

**Issue by evils** [tweag/nix-hour#56]
mostly from here: https://github.com/NixOS/nixpkgs/issues/255657

fetchZip unpacks the source but the unpacked source exceeds the hydra size limit
so even though the package that uses the source outputs something way below the limit, it can't be built on hydra

additionally it may be interesting to look at
fetchFromGitHub -> fetchZip -> fetchurl -> maybe even mirrors?
(and how the software heritage foundation could factor into this?)

and when one may want to stop stuff from buildng on Hydra (and how to do so)
when to set up your own cache
and maybe even talk about the prospects for P2P stores?

**Comment by infinisil** [comment]
We're going to cover this topic in this weeks Nix Hour on Wednesday 15:00 CEST! If you or anybody else has any extra questions about this topic, either:

- Ask them in this issue in advance with a comment
- Join the [livestream](https://youtube.com/live/1j82aNGATTU) and use the chat to ask questions live
