### ISSUE TITLE
Lookup path syntax

### ISSUE THREAD

**Issue by PicoGeyer** [tweag/nix-hour#58]
I originally installed NixOS with version 22.11 and later transitioned my configuration to use flakes
I often use `nix repl` to explore the layout of nixpkgs, but lately I discovered that `<nixpkgs>`
 still points to a 22.11 version of nixpkgs whereas my system is now on 23.11.

How can I set NIX_PATH such that it points to the current version of nixpkgs that I'm using as seen from the flake point of view?
I've seen: https://search.nixos.org/options?channel=23.11&show=nix.nixPath&from=0&size=50&sort=relevance&type=packages&query=nix.nixPath
But I'm not sure what I would set it to so that it follows the flake version of nixpkgs.

**Comment by infinisil** [comment]
We're going to focus on [lookup paths](https://nixos.org/manual/nix/stable/language/constructs/lookup-path.html#lookup-path) in general for this weeks Nix Hour, this Friday at 17:00 CET! If anybody has any extra questions about this topic, either:

- Ask them in this issue in advance with a comment
- Join the [livestream](https://youtube.com/live/0eGz_Oly31o) and use the chat to ask questions live
