### ISSUE TITLE
Filtering sources

### ISSUE THREAD

**Issue by terlar** [tweag/nix-hour#6]
What are the alternatives to filter sources and explain benefits of source filtering and how it can speed up derivations.

I guess this could go into the basics of `builtins.path`, then enter into the filtering functions provided by nixpkgs and how some filtering can be composed and then perhaps even the different third party libraries assisting with this for example git-based filtering.

**Comment by infinisil** [comment]
Covered [in the last Nix Hour :)](https://youtu.be/mOQI9Iiu4Uc?t=138)

**Comment by terlar** [comment]
Thank you, watched it and I think it covered most of the stuff. One thing that seems quite useful that I haven't looked at personally is this one as well:
https://github.com/numtide/nix-filter
