### ISSUE TITLE
Impure runtime dependencies

### ISSUE THREAD

**Issue by infinisil** [tweag/nix-hour#61]
Derivations occasionally need dependencies that are impractical to provide purely in the build, which leads to problems and workarounds. For example:
- Graphics drivers depend on your graphics card, it's impractical to hard-code the driver into all package builds, so NixOS uses `/run/opengl-driver/lib`. Related: https://github.com/NixOS/nixpkgs/pull/269475
  - See also https://github.com/tweag/nix-hour/issues/55
- Locales
- Glibc nss modules
- Custom CA certificates
- Timezones
- ...

I previously sketched a potential solution here: https://gist.github.com/infinisil/3366e7dfc9a01f6eeb25b5cb475cc585

---

We decided to focus on this topic for this weeks Nix Hour, this Friday at 15:00 CET! If you have any questions about this topic, either:

- Ask them in this issue in advance with a comment
- Join [the meeting](https://meet.zrh.init7.net/nix-hour) and ask using voice or chat

And if you just want to listen in, it's going to be streamed to YouTube [here](https://www.youtube.com/live/jNIJ8HWi7aM?feature=shared) 🙂

**Comment by infinisil** [comment]
New meeting link: https://meet.jit.si/the-nix-hour

**Comment by patryk4815** [comment]
Today I had issue with glibc nss on rhel linux. Solved by:
```
ln -s /lib64/libnss_sss.so.2 /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libnss_sss.so.2
```
I don't like non-Nixos problems 😞

**Comment by infinisil** [comment]
Yeah it's not great, lot of improvement potential!

For now I'll close this issue since we talked about this last time :)
