### ISSUE TITLE
Getting Started Reading the Nixpkgs source.

### ISSUE THREAD

**Issue by TheZombie1999** [tweag/nix-hour#7]
Hi when i trie to develop a nix derivation i often run into problems.
To solve these issues i would be of great benifit to start reading the nixpkgs source code. But when i try read the source i can never find what i need. It would be great if you could give a briev overview how 
nixpkgs is structured and where one can find common nix expressions.

One of the most common expressions that i would like to look up 
ist stdenv.mkDerivation maybe you could use this as a starting point.

**Comment by infinisil** [comment]
We covered a lot of this in the last [Nix Hour #13](https://youtu.be/Vca3meCWaLo). While there's more things I could cover, please write another comment with more specifics or a separate issue :)
