### ISSUE TITLE
Utilising the Nix 2.12 features regarding builds

### ISSUE THREAD

**Issue by 573** [tweag/nix-hour#9]
It would be nice to be able to adopt the new https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-auto-allocate-uids and https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-use-cgroups in my ci build.

Is there a possibility to explain the background of the settings a bit and maybe come up with a minimal, i. e. but not neccessarily github-action, workflow file.

**Comment by infinisil** [comment]
We might look into this a bit after all, because this week the topic is going to be various experimental features: https://github.com/tweag/nix-hour/issues/65!
